Repository nimblehq/compass-credo-plugin, pull requests merged in 2022-09, with the labels that each got.

#10 [#9] Ordering of defdelegate
  coveralls.json
  lib/check/.keep
  lib/check/defdelegate_order.ex
  lib/compass_credo_plugin.ex
  mix.exs
  mix.lock
  priv/.credo.exs
  test/check/defdelegate_order_test.exs
Labels: type : feature, check

#15 [#3] Avoid repeating fragments in module names and namespaces
  lib/check/repeating_fragments.ex
  priv/.credo.exs
  test/check/repeating_fragments_test.exs
Labels: check

#11 [#8] Publish the package to Hex
  mix.exs
  mix.lock
Labels: type : chore, on hold

#13 [#12] Add MIT license file
  LICENSE
Labels: type : chore

#14 [#1] Use "do:" with single statement if/unless and def/defp
  lib/check/do_single_expression.ex
  priv/.credo.exs
  test/check/do_single_expression_test.exs
Labels: check

#18 [Chore] Bump version to 1.0.0
  mix.exs
Labels: type : chore

#17 Release 1.0.0
  LICENSE
  coveralls.json
  lib/check/.keep
  lib/check/defdelegate_order.ex
  lib/check/do_single_expression.ex
  lib/check/repeating_fragments.ex
  lib/check/single_module_file.ex
  lib/compass_credo_plugin.ex
  mix.exs
  mix.lock
  priv/.credo.exs
  test/check/defdelegate_order_test.exs
  test/check/do_single_expression_test.exs
  test/check/repeating_fragments_test.exs
  test/check/single_module_file_test.exs
Labels: type : release
